esphome:
  name: dolly2
  platform: ESP32
  board: esp32cam
  includes:
    - Custom32.h

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_pwd

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dolly2 Fallback Hotspot"
    password: !secret ota_pwd



# Example configuration entry
esp32_camera:
  name: Dolly2
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1280x1024
  # Example configuration entry
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

# Pir sensor  
binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "Garage PIR Sensor"
    device_class: motion

# Example configuration entry
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
    
light:
  - platform: binary
    output: gpio_4
    name: dolly2 light

switch:
  - platform: gpio
    pin: GPIO12
    name: IrCut R
    id: IrCutR
   # restore_mode: always_off
    icon: "mdi:gate"
    interlock: [IrCutL]
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: IrCutR


  - platform: gpio
    pin: GPIO14
    name: "IrCut L"
    id: IrCutL
    #restore_mode: always_off
    icon: "mdi:gate"
    interlock: [IrCutR]
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: IrCutL



web_server:
  port: 80
  auth:
    username: camadmin
    password: !secret web_server_password

