esphome:
  name: dolly2
#  board: esp32cam
  includes:
  - Mesh32RC.h

esp32:
  board: esp32dev
  framework:
    type: arduino



# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pwd

ota:
  password: !secret ota_pwd

wifi:
# Local MAC: 40:F5:20:79:4A:B0
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  power_save_mode: none
  reboot_timeout: 24h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dolly2 Fallback Hotspot"
    password: !secret ota_pwd



# Example configuration entry
esp32_camera:
  name: dolly2
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 1280x1024
  horizontal_mirror: False
  vertical_flip: False
  # Example configuration entry
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

custom_component:
  - lambda: |-
        Mesh32RC::begin(9);
        Mesh32RC::on("ESP32 dolly", [](const uint8_t* st, uint8_t l) {
        	//String st = MeshRC::getValue();
          ESP_LOGD("ESP_last", "Unhandled mesage: ESP32 dolly%s", st);
         });
        return {};

# Pir sensor  
binary_sensor:
  - platform: gpio
    pin: GPIO13
    name: "dolly2 PIR Sensor"
    device_class: motion

# Example configuration entry
sensor:
  - platform: wifi_signal
    name: "dolly2_wifi_signal"
    update_interval: 180s
    on_value:
    - lambda: Mesh32RC::send("dolly2 Wifi_signal= "+(String)x);

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
    
light:
  - platform: binary
    output: gpio_4
    name: dolly2 light
    on_turn_on:
    - lambda: Mesh32RC::send("dolly2 turn_light= ON");
              Serial.println("dolly2lightON");

switch:
  - platform: gpio
    pin: GPIO12
    name: "dolly2 IrCut R"
    id: IrCutR
   # restore_mode: always_off
    icon: "mdi:gate"
    interlock: [IrCutL]
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: IrCutR


  - platform: gpio
    pin: GPIO14
    name: "dolly2 IrCut L"
    id: IrCutL
    #restore_mode: always_off
    icon: "mdi:gate"
    interlock: [IrCutR]
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: IrCutL

  - platform: template
    #pin: GPIO15
    name: "dolly2_Reboot"
    optimistic: true
    on_turn_on:
        - lambda: ESP_LOGD("dolly2", "reboot started");
            Mesh32RC::Reboot();
          

web_server:
  port: 80
  auth:
    username: camadmin
    password: !secret web_server_password

