esphome:
  name: espcam-a
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_ssid

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espcam-A Fallback Hotspot"
    password: !secret ota_pwd

captive_portal:
