esphome:
  name: kitchentemp
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_pwd

ota:
  password: "olemat4711"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "room1 Hotspot"
    password: !secret ota_pwd

captive_portal:
