esphome:
  name: wemostemp
  platform: ESP8266
  board: d1_mini
  includes:
  - MeshRC.h

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_pwd

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.105
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.0.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemostemp Fallback Hotspot"
    password: !secret ota_pwd
    
custom_component:
  - lambda: |-
        MeshRC::begin(9);
        MeshRC::on("ESP01 E8:DB:84:99:23:ED Started", []() {
         id(PIR_Sensor)->publish_state(true);
         ESP_LOGD("ESP01 E8:DB:84:99:23:ED ", "Started");
         });
        MeshRC::on("ESP01 BC:DD:C2:E6:29:B3 Started", []() {
         id(FrontGate)->publish_state(true);
         ESP_LOGD("ESP01 BC:DD:C2:E6:29:B3 ", "Started");
         });
        MeshRC::on("Internal_led esp12-a off", []() {
          id(PIR_Sensor)->publish_state(false);
          MeshRC::send("my_remote-esp32-w-32d-1 from esp12a off");
         });
        MeshRC::on("ESP", [](unsigned char* st, unsigned l) {
        	//String st = MeshRC::getValue();
          ESP_LOGD("ESP_last", "Unhandled mesage: ESP%s", st);
         });
        MeshRC::on("dolly", [](unsigned char* st, unsigned l) {
        	//String st = MeshRC::getValue();
          ESP_LOGD("ESP_last", "Unhandled mesage: dolly%s", st);
         });
        return {};
   

captive_portal:
# Example configuration entry
remote_transmitter:
  pin: 
    number: GPIO14
    inverted: true
  carrier_duty_percent: 100%

dallas:
  - pin: 2

# Pir sensor  
switch:
  - platform: template
    name: "PIR_Sensor"
    id: "PIR_Sensor"
    optimistic: true 
    #device_class: motion
    on_turn_on:
    - delay: 60s
    - switch.turn_off: PIR_Sensor

  - platform: template
    name: "FrontGate"
    id: "FrontGate"
    #device_class: motion
    optimistic: true 
    on_turn_on:
    - delay: 60s
    - switch.turn_off: FrontGate
    
  - platform: template
    name: Vrum_read_lamp
    optimistic: true 
    # nexa D3
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
         code: '010100000001000000010101'
         repeat:
            times: 10
            wait_time: 0s
         protocol: 6

    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
         code: '010100000001000000010100'
         repeat:
            times: 10
            wait_time: 0s
         protocol: 6


  - platform: template
    name: sov_J_lamp
    optimistic: true 
    #nexa D2
    turn_on_action:
      - remote_transmitter.transmit_rc_switch_raw:
         code: '010100000100000000010101'
         repeat:
            times: 10
            wait_time: 0s
         protocol: 6
    turn_off_action:
      - remote_transmitter.transmit_rc_switch_raw:
         code: '010100000100000000010100'
         repeat:
            times: 10
            wait_time: 0s
         protocol: 6
  

# Individual sensors
sensor:
  - platform: dallas
    address: 0xEF03139779C89228
    name: "kök Temperature"
    filters:
      - or:
        - throttle: 10min
        - delta: 0.5
    

  - platform: dallas
    address: 0xAA03079779959728
    name: "dusch Temperature"
    filters:
      - or:
        - throttle: 5min
        - delta: 1.0

  - platform: dallas
    address: 0x3a3c01d607f8f328
    name: "in 1.5 Temperature"
    filters:
      - or:
        - throttle: 5min
        - delta: 1.0
  
  - platform: dallas
    address: 0x873c01d0756a0428
    name: "out 3.0 Temperature"
    filters:
      - or:
        - throttle: 5min
        - delta: 1.0
  
